#!/bin/bash
#
# Title:      PGBlitz (wallabag/wallabag)
# Author(s):  MrDoob
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'wallabag'
        intport: '80'
        extport: '8090'      
        image: 'wallabag/wallabag'
        #env_file: '/var/data/config/wallabag/wallabag.env'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

   # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          #traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.backend: '{{pgrole}}'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.http.routers.wallabag.middlewares: 'wallabagHeaders'
          traefik.http.middlewares.wallabagHeaders.headers.sslProxyHeaders.X-Forwarded-Proto: 'https'
          traefik.frontend.whiteList.useXForwardedFor: 'true'
          traefik.frontend.redirect.regex: '^http://wallabag.andriu.top/(.*)'
          traefik.frontend.redirect.replacement: 'https://wallabag.andriu.top/$$1'
          traefik.frontend.redirect.permanent: 'true'
          com.centurylinklabs.watchtower.enable: 'true'
          TRUSTED_PROXIES: '10.0.0.0/8,192.168.0.0/16'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/data:/var/www/wallabag/data:rw'
          - '/opt/appdata/{{pgrole}}/images:/config/var/www/wallabag/web/assets/images:rw'        
          - '{{path.stdout}}:{{path.stdout}}'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: '${TZ}'
          SYMFONY__ENV__FOSUSER_REGISTRATION: 'false'
          SYMFONY__ENV__DOMAIN_NAME: 'https://wallabag.andriu.top'     

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'    
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
