#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts wekan-db'
      set_fact:
        pgrole0: 'wekandb'
        intport0: '27017'
        extport0: '27017'
        image0: 'quay.io/wekan/mongo:4.4.2-bionic'
        
    - name: 'Set Known Facts wekan'
      set_fact:
        pgrole1: 'wekan'
        intport1: '80'
        extport1: '4546'
        image1: 'quay.io/wekan/wekan'
 
    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'
      
    # LABELS ################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting PG Volumes wekan-db'
      set_fact:
        pg_volumes:
          - /opt/appdata/wekan/db:/data/db
          - /opt/appdata/wekan/dump:/dump
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV wekan-db'
      set_fact:
        pg_env0:
          PUID: '1000'
          PGID: '1000'
          
    - name: 'Setting PG ENV wekan'
      set_fact:
        pg_env1:
          PUID: '1000'
          PGID: '1000'
          MONGO_URL: 'mongodb://wekandb:27017/wekan'
          ROOT_URL: 'https://wekan.andriu.xyz'
          MAIL_URL: 'smtp://wekan:wekan@mailserver:25'
          MAIL_FROM: 'Wekan Notifications <noreply.wekan@andriu.xyz>'
          WITH_API: 'true'
          RICHER_CARD_COMMENT_EDITOR: 'false'
          CARD_OPENED_WEBHOOK_ENABLED: 'false'
          BIGEVENTS_PATTERN: 'NONE'
          BROWSER_POLICY_ENABLED: 'true'

    # MAIN DEPLOYMENT ##############################################################

    - name: 'Deploying {{pgrole0}}'
      docker_container:
        name: '{{pgrole0}}'
        image: '{{image0}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport0}}:{{intport0}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env0}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole0}}'
        state: started
  
    - name: 'Deploying {{pgrole1}}'
      docker_container:
        name: '{{pgrole1}}'
        image: '{{image1}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport1}}:{{intport1}}'
        env: '{{pg_env1}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole1}}'
        state: started
        labels: '{{pg_labels}}'
